Metadata extension changes clean
OliverEGreen/Dynamo pull request #2
Opened 2021-06-30 14:13 UTC by OliverEGreen

Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

2021-06-30 16:02 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        private void InitializeRequiredProperties()
If there arent any specific reason from duplicating it i would say its best to only have this collection in PreferenceSettings. The methods for adding and removing should probably also live there and the viewModel commands would just call those

```csharp
private void AddRequiredProperty(object obj)
{
    RequiredProperty requiredProperty = new RequiredProperty
     {
          Key = $"Required Property {RequiredProperties.Count + 1}",
          Value = ""
      };

    preferenceSettings.AddRequiredProperty(requiredProperty)
}

2021-07-01 07:52 UTC, SHKnudsen requested changes

2021-07-01 07:52 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            this.AddRequiredPropertyCommand = new DelegateCommand(AddRequiredProperty);
Wondering if we should disable this command if there are any duplicated Keys, so users can add more key until they fix the duplicate

2021-07-01 07:52 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        /// Toggles whether a RequiredProperty has its value set globally, or per-graph
maybe add a small comment about what globally means

2021-07-01 07:52 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Menu/PreferencesView.xaml
> +                        <!--  This Grid contains the package manager settings tab  -->
This seems wrong 😁

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewExtension.cs
> +                    if (customPropertiesToBuild.ContainsKey(keyValuePair.Key)) continue;
i dont think this can actually ever have duplicates, can it?
As we are looping over `ExtensionData` which is a Dictionary, and dictionaries cant have duplicated keys

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewExtension.cs
> +                ExtensionRequiredProperty extensionRequiredProperty = this.viewModel.ExtensionRequiredProperties.FirstOrDefault(x => x.Key == keyValuePair.Key);
split up Linq

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewExtension.cs
> +            foreach (ExtensionRequiredProperty extensionRequiredProperty in viewModel.ExtensionRequiredProperties)
so essentially, if there are duplicates between custom properties and required properties, required takes priority and overwrites custom?

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        public Visibility ExtensionRequiredPropertiesVisibility
`bool` instead and the use converter in xaml

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        public Visibility ExtensionRequiredPropertiesVisibility
also needs a summary

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        /// Collection of Properties Required by this ViewExtension
What do we mean by `Required by this ViewExtension`

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +            }
this seems to be very similar to things you were doing in the viewExtension. If its necessary to do this in both places would it be possible to have one internal method that does this?

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void OnCurrentWorkspaceChanged(IWorkspaceModel obj)
FYI this is where you would need to clean up things when the workspace changes

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +                case "Key":
can we us `nameof` here => `nameof(RequiredProperty.Key)`

2021-07-01 07:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void RequiredPropertyNamesOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
Should this name just be `OnRequiredPropertyCollectionChanged`? not sure i understand the `Names` part

2021-07-01 08:22 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        public Visibility RequiredPropertiesDuplicateKeyWarningVisibility
Updated!

2021-07-01 08:25 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            PythonEnginesList.Add(Res.DefaultPythonEngineNone);
Sorry I think this was ReSharper being clever. I think it's picking up that Res. is an alias for Wpf.Properties.Resources. It's suggesting the change everywhere it sees it. I saw the suggestion and took it! Can either undo or can apply file/project-wide.

![image](https://user-images.githubusercontent.com/29973601/124091851-294abc00-da4e-11eb-87cb-c0d76428fc72.png)

2021-07-01 08:32 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            bool duplicatesExist = numberOfUniqueKeys != numberOfKeys && numberOfKeys >= 2;
Yep sorted!

2021-07-01 08:54 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        internal bool CheckDuplicateRequiredPropertyKeysExist()
Updated to private and added in a summary. 
Renamed method to CheckForRequiredPropertyDuplicateKeys. Happy to take better naming recommendations here, it's still rather clunky!

2021-07-01 08:55 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        internal void UpdateRequiredPropertiesDuplicateKeyWarningVisibility(bool visible)
Yes - updated

2021-07-01 08:59 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            RequiredProperty requiredPropertyToUpdate = preferenceSettings.RequiredProperties.FirstOrDefault(x => x.Key == requiredProperty.Key);
👍

2021-07-01 09:00 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            // requiredPropertyToUpdate.Key = requiredProperty.Key;
Oops unnecessary code. Removed!

2021-07-01 09:20 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            PythonEnginesList.Add(Res.DefaultPythonEngineNone);
Ah, see! I would probably undo this one, otherwise we need to be prepared for questions around it when opening the PR to Dynamo

2021-07-01 09:20 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        internal bool CheckDuplicateRequiredPropertyKeysExist()
Thanks, that name makes sense to me 👍

2021-07-01 09:23 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            PythonEnginesList.Add(Res.DefaultPythonEngineNone);
Cool undone!

2021-07-01 09:24 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        private void InitializeRequiredProperties()
In order to set the ListView's ItemsSource to an ObservableCollection in another namespace/class, I think it may need to be static?

2021-07-01 09:25 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        private void InitializeRequiredProperties()
Am just reading this: 

https://stackoverflow.com/questions/35346603/binding-to-a-property-in-another-namespace

2021-07-01 09:34 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        private void InitializeRequiredProperties()
My thought was that there would still be a required property on the view model, but would just be something like this
```csharp
/// <summary>
/// Gets RequiredProperty collection from PreferenceSettings, this is only for binding in the UI
/// </summary>
ObservableCollection<RequiredProperty> RequiredProperties => preferenceSettings.RequiredProperties
```
As it is an ObservableCollection **(i think!)** every time you add to RequiredProperties on PreferenceSettings the UI will automatically know as RequiredProperties should raise property change.

This would ensure that we dont have to worry about keeping two RequiredProperties collections in sync, we only ever interact with PreferenceSettings RequiredProperties and just have a reference to that in the viewModel for binding purposes.

2021-07-01 09:36 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        private void InitializeRequiredProperties()
Ooh never seen lambda syntax for a property before. Love it!

2021-07-01 16:05 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +                case "Key":
Done!

2021-07-01 16:06 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void RequiredPropertyNamesOnCollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
Updates this to RequiredPropertiesOnCollectionChanged

2021-07-01 16:06 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +            }
Done

2021-07-01 16:07 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        /// Collection of Properties Required by this ViewExtension
Changed to `Collection of RequiredProperties`

2021-07-01 16:08 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewExtension.cs
> +                ExtensionRequiredProperty extensionRequiredProperty = this.viewModel.ExtensionRequiredProperties.FirstOrDefault(x => x.Key == keyValuePair.Key);
Done, will do in the future!

2021-07-01 16:15 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/Menu/PreferencesView.xaml
> +                        <!--  This Grid contains the package manager settings tab  -->
Updated!

2021-07-01 16:17 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        /// Toggles whether a RequiredProperty has its value set globally, or per-graph
Done

2021-07-01 16:18 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        public Visibility ExtensionRequiredPropertiesVisibility
Done

2021-07-01 16:18 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        public Visibility ExtensionRequiredPropertiesVisibility
Renamed to `IsRequiredPropertiesVisible`

2021-07-01 16:20 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewExtension.cs
> +                    if (customPropertiesToBuild.ContainsKey(keyValuePair.Key)) continue;
D'oh. Removed redundant code.

2021-07-01 16:34 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        private void InitializeRequiredProperties()
Done.

2021-07-01 16:34 UTC, OliverEGreen commented on src/DynamoCore/Configuration/RequiredProperty.cs
> +    public class RequiredProperty : NotificationObject
Done

2021-07-01 16:53 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +            this.AddRequiredPropertyCommand = new DelegateCommand(AddRequiredProperty);
I've set this command's Button to have IsEnabled off when the warning is displaying. 
It might not be super evident to the user that the button's disabled, though. 
Will need to test.

2021-07-02 10:39 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void OnCurrentWorkspaceChanged(IWorkspaceModel obj)
We did originally clear RequiredProperties here, but I think it might be causing us some issues.

The GraphMetadataViewModel fires when Dynamo opens. I load in the RequiredProperties from the XML during its constructor, so that if I open the New Home file immediately after loading Dynamo, it will display RequiredProperties.

-> If I clear RequiredProperties here, any RequiredProperties loaded in earlier will be removed, since OnCurrentWorkspaceChanged fires after the GraphMetadataViewModel constructor. 
-> However, if I don't clear RequiredProperties here, then we'll carry them over from the previous graph when a new graph is created.

So I'm moving the call to InitializeRequiredProperty to go right after clearing them. That seems to work the way we want it to.

2021-07-02 10:54 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void OnCurrentWorkspaceChanged(IWorkspaceModel obj)
Correct me if I'm wrong here, but we only need to clear the values right? So could we not just set all GraphValues to null or string.Empty here?

2021-07-02 11:06 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void OnCurrentWorkspaceChanged(IWorkspaceModel obj)
That's right - we also need to populate the values in this moment, so I think clearing and rebuilding is gonna have the same end effect.

2021-07-02 11:09 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void OnCurrentWorkspaceChanged(IWorkspaceModel obj)
Actually I might be wrong, this might be behind an edge case bug I'm coming up against :)

2021-07-02 11:36 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +        private void OnCurrentWorkspaceChanged(IWorkspaceModel obj)
Yup that was it. Updated!

2021-07-05 08:52 UTC, SHKnudsen requested changes
@OliverEGreen looks really good, just a few small things..

we might want to consider a test or two about setting the value of a required property, so one for global value and on for graph value

2021-07-05 08:52 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +using System.Collections.Specialized;
Do you know what this one is for?

2021-07-05 08:52 UTC, SHKnudsen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +                case "ValueIsGlobal":
`nameof` on these

2021-07-05 08:52 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +        public void PreferenceSettingsAddRequiredProperty()
This should probably be a test in `PreferenceSettings` tests, shouldnt it?

2021-07-05 08:52 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +        public void PreferenceSettingsAddRequiredProperty()
And if it should, we can just call it `CanAddRequiredProperty`

2021-07-05 08:52 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +            var preferenceSettings = this.ViewModel.PreferenceSettings;
NIT: this should probably be in the `Arrange` section

2021-07-05 08:52 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +            graphMetadataViewExtension.viewModel.RequiredProperties.Clear();
Do we actually need to clear both? does the viewModel not do that automatically when the preferenceSettings gets cleared?

2021-07-06 10:21 UTC, OliverEGreen commented on src/DynamoCore/Configuration/RequiredProperty.cs
>      public class RequiredProperty : NotificationObject
Done

2021-07-06 10:22 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +using System.Collections.Specialized;
This one is needed for NotifyCollectionChangedEventArgs, when we're listening to an ObservableCollection's CollectionChanged event. I'd say we need it

2021-07-06 10:25 UTC, OliverEGreen commented on src/GraphMetadataViewExtension/GraphMetadataViewModel.cs
> +                case "ValueIsGlobal":
Done!

2021-07-06 10:25 UTC, OliverEGreen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +            var preferenceSettings = this.ViewModel.PreferenceSettings;
Done

2021-07-06 10:30 UTC, OliverEGreen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +            graphMetadataViewExtension.viewModel.RequiredProperties.Clear();
Given that the test starts Dynamo fresh, probably not. 
The ViewExtension listens for CollectionChanged and for each item's PropertyChanged. However, Clear() isn't picked up by either of these events, so clearing the PreferenceSettings' RequiredProperties shouldn't affect the ViewExtension's. We don't deal with this since there's no way to call Clear() via the UI.

2021-07-06 10:46 UTC, OliverEGreen commented on test/DynamoCoreWpfTests/ViewExtensions/GraphMetadataViewExtensionTests.cs
> +        public void PreferenceSettingsAddRequiredProperty()
Done! Moved to PreferencesViewModelTests

2021-07-06 11:22 UTC, OliverEGreen commented
Responded to all comments above.

2021-07-06 18:31 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        internal ObservableCollection<RequiredProperty> RequiredProperties => this.preferenceSettings.RequiredProperties;
hm does this actually work in terms of binding?

2021-07-07 09:05 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Menu/PreferencesViewModel.cs
> +        internal ObservableCollection<RequiredProperty> RequiredProperties => this.preferenceSettings.RequiredProperties;
set back to public

2021-07-07 09:33 UTC, SHKnudsen approved these changes

2021-07-07 09:57 UTC, merged