Node redesign
OliverEGreen/Dynamo pull request #3
Opened 2021-07-22 15:08 UTC by OliverEGreen

Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

2021-07-22 16:03 UTC, SHKnudsen requested changes

2021-07-22 16:03 UTC, SHKnudsen commented on src/Libraries/PythonNodeModelsWpf/PythonNode.cs
> +            nodeView.MainContextMenu.Items.Insert(11, learnMoreItem);
just out of curiosity, why are we using `Insert` with an index instead of just `Add`?

2021-07-22 16:10 UTC, OliverEGreen commented on src/DynamoCore/Configuration/Configurations.cs
> +        public static readonly double CodeBlockOutputPortHeightInPixels = 20;
Added back in

2021-07-22 16:11 UTC, OliverEGreen commented on src/DynamoCore/Graph/Nodes/NodeModel.cs
> +using Dynamo.Search.SearchElements;
done

2021-07-22 16:15 UTC, OliverEGreen commented on src/DynamoCore/Graph/Nodes/PortModel.cs
> +                        }
// Special case because code block outputs are smaller than regular outputs.
// This ensures the output port of the first code block output aligns with
// the first input port of any node.

2021-07-22 16:17 UTC, OliverEGreen commented on src/DynamoCore/Graph/Nodes/PortModel.cs
> +        public void RaisePortIsConnectedChanged()
changed to private

2021-07-22 16:22 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Converters.cs
> +                    return NoneBrush;
Returned back to how it was. 
They were using this to style the node border when it gets clicked, but tbh that's no good. 
Now it's handled differently anyway so can restore this to just dealing with Connections.

2021-07-22 16:24 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Converters.cs
> -    public class StateToColorConverter : IValueConverter
We're handling this all through the PortViewModel's RefreshPortColors now. 
The logic got too complex for a converter.

2021-07-22 16:28 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Converters.cs
> +    public class NodeOriginalNameToMarginConverter : IValueConverter
"Used to ensure input and output ports are set to the right height.
There is a special case for code block output ports: the first code block output port should
align with the first port on any other node, despite being different sizes. The offset is achieved using the margin."

2021-07-22 16:29 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/NodeViewModel.cs
> +using Size = System.Windows.Size;
Tidied!

2021-07-22 16:31 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +        public bool IsPortCondensed
Any ideas? IsPortCodeBlockOutputPort?

2021-07-22 16:32 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +        }
It isn't! Don't actually know when / how this happened :)

2021-07-22 16:32 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +        }
Reverted back

2021-07-22 16:34 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +        private PortEventType eventType;
Removed this field! Moved _showUseLevelMenu up to the top among the other private fields.

2021-07-22 16:35 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +            RefreshPortColors();
True, changed to run when the port is connected/disconnected and when the list structure keeping is changed.

2021-07-22 16:38 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs
> +            };
Something like:
// Note: This was moved above the below 4 lines so that node icons could be retrieved.
// Doing this relies on having access to the InCanvasSearchViewModel / SearchViewModel.

2021-07-22 16:43 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Search/SearchViewModel.cs
> +        internal ImageSource GetNodeIcon(NodeViewModel nodeViewModel)
Great, adjusted!

2021-07-22 16:43 UTC, OliverEGreen commented on src/Libraries/CoreNodeModelsWpf/NodeViewCustomizations/DSDropDownBase.cs
> +                VerticalAlignment = VerticalAlignment.Center,
;)

2021-07-22 16:44 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/Core/NodeView.xaml.cs
> +            if (ViewModel.WorkspaceViewModel.Zoom < 0.4)
Right click is no longer handled - the Asana task said left click I thought?

2021-07-22 16:46 UTC, OliverEGreen commented on src/Libraries/PythonNodeModelsWpf/PythonNode.cs
> +            nodeView.MainContextMenu.Items.Insert(11, learnMoreItem);
We want them to appear at a specific place/Index in the ContextMenu rather than just being added to the bottom of the list.

2021-07-22 16:47 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +                        PortBorderBrushColor = (SolidColorBrush)SharedDictionaryManager.DynamoColorsAndBrushesDictionary["PortDefaultBorderBrush"];
Didn't understand this one :D

2021-07-23 08:16 UTC, OliverEGreen commented on src/DynamoCore/Graph/Nodes/PortModel.cs
> +        public void RaisePortIsConnectedChanged()
changed again to internal

2021-07-23 08:24 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +                return false;
Switched to _port.IsConnected

2021-07-23 08:45 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/PortViewModel.cs
> +        public bool IsPortCondensed
/// <summary>
        /// Sets the condensed styling on Code Block output ports.
        /// This is used to style the output ports on Code Blocks to be smaller.
        /// </summary>

2021-07-23 08:49 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/WorkspaceViewModel.cs
> +            };
// InCanvasSearchViewModel needs to happen before the nodes are created
            // as we rely upon it to retrieve node icon images

2021-07-26 08:20 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/Core/NodeView.xaml.cs
> +            if (ViewModel.WorkspaceViewModel.Zoom < 0.4)
Confirmed with Sol they want left-click here.

2021-07-26 09:00 UTC, SHKnudsen approved these changes

2021-07-26 16:29 UTC, OliverEGreen commented
What shall we do with this now?

2021-07-26 16:52 UTC, SHKnudsen commented
> What shall we do with this now?

@OliverEGreen was that feature branch ever created?

2021-07-26 17:06 UTC, OliverEGreen commented
> > What shall we do with this now?
> 
> @OliverEGreen was that feature branch ever created?

I think it's this one here: 
https://github.com/DynamoDS/Dynamo/compare/DynamoNodeRedesign...master

2021-07-26 17:16 UTC, SHKnudsen commented
Cool lets make a PR to `DynamoNodeRedesign` then

2021-07-28 09:34 UTC, merged