Node informational states
OliverEGreen/Dynamo pull request #4
Opened 2021-08-03 16:54 UTC by OliverEGreen

### Purpose

This PR introduces a new design to the InfoBubble UserControl, which is used to report node warnings and errors to the user. 

There are now 3 kinds of user-facing messages a node can display. In order of ascending severity, these are Info, Warning and Message. 

The InfoBubble is now capable of displaying multiple info messages, warnings and errors simultaneously, and gives the user the ability to dismiss both Warnings and Info Messages. Errors cannot be dismissed. 

Dismissed messages may be retrieved by the node's context menu.

The following GIFs demonstrate the new functionality added in this PR:

![DismissingMessages](https://user-images.githubusercontent.com/29973601/127996336-c9757ff9-0a34-43dd-b8f8-cf2c8ac65344.gif)

1. User-facing messages may now be dismissed by the user, and undismissed using the node's context menu. When messages are dismissed, a small counter glyph appears at the base of the node whose messages were dismissed. 

![StackingMessages](https://user-images.githubusercontent.com/29973601/127996406-70e81171-e34f-439b-aed1-d6a1170773c5.gif)

2. Messages may be stacked according to their severity level. Errors (if any) will always appear at the base of the stack, with warnings above and info messages at the highest level. Each level of the stack may be expanded and contracted by clicking on the message body.

The message body may take 1 of 3 states:

- A simple icon, with no messages displayed. This is the most compact representation.
- An icon alongside the first message at the corresponding severity level, e.g. Errors. Where there are multiple messages at this level, an iterating counter appears beside each message.
- Where multiple messages are present at the same severity level, clicking 'show all' will expand all messages at this level. An interating counter will be displayed to help users keep track of the messages.

![ScrollingMessages](https://user-images.githubusercontent.com/29973601/127996438-0fa55cd5-2f5c-4f09-ab4f-c57716c02a68.gif)

3. A maximum height has been set per message-level, in case warning messages are very long (such as a long Python traceback message). In such cases, a scrollbar appears to allow for convenient traversal and review of any messages. 

### Impact assessment

- [ ] Changes the way 3rd party nodes work (Add ikeough to the reviewer list)
- [ ] Includes migrations (Add ikeough to the reviewer list)
- [ ] Adds or changes a public interface (Add lukechurch to the reviewer list)
- [ ] API change is added to the [API Changes document](https://github.com/DynamoDS/Dynamo/wiki/API-Changes).
- [ ] Affects which components of the system depends on which other components (Add pboyer to the reviewer list)
- [ ] Introduces new components (Add lukechurch to the reviewer list)
- [ ] Has a performance impact (Add keyu to the reviewer list)
- [ ] Changes the installer (Add sharadkjaiswal to the reviewer list)
- [X] User facing strings, if any, are extracted into `*.resx` files
- [X] All tests pass using the self-service CI.
- [X] Snapshot of UI changes, if any.

#### References (FILL ME IN)

The Dynamo team already has links to the new UI design.

#### Testing strategy

These changes have been tested manually in DynamoSandbox, with a range of generated Info Messages, Warnings and Errors.
Two tests have been added to DynamoCoreWpfTests/InfoBubbleTests.

### Review staging

- [ ] Architectural Design Review
- [X] UI Review

### Reviewers

Aaron (to be added in the real PR)

### FYIs

SolAmour (to be added in the real PR)

2021-08-03 18:21 UTC, SHKnudsen requested changes

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +            switch (nodeMessageVisibility)
can we try and condense this a little? it seems like each case in the switch is doing similar things with a few modifications, can we extract everything that is the same to private method(s)

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        public string LinkText { get; set; }
summary

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +            double estimatedWidth)
put each argument on its own line

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +            double estimatedWidth)
same as above

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +            //margin.Left = -((estimatedWidth - nodeWidth) / 2) + ViewModel.TargetTopLeft.X;
we should be able to remove this entire method, right?

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +            }
```suggestion
            // If we're already expanded, this button collapses the border
            if (ViewModel.NodeErrorsVisibilityState == InfoBubbleViewModel.NodeMessageVisibility.ShowAllMessages)
            {
                ViewModel.NodeErrorsVisibilityState = InfoBubbleViewModel.NodeMessageVisibility.CollapseMessages;
                ViewModel.NodeErrorsShowLessMessageVisible = false;
                return;
            }
            // Otherwise it expands the border
            ViewModel.NodeErrorsVisibilityState = InfoBubbleViewModel.NodeMessageVisibility.ShowAllMessages;
            ViewModel.NodeErrorsShowLessMessageVisible = true;
```

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +        private void ShowAllWarningsButton_Click(object sender, RoutedEventArgs e)
same suggestion as above

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +        private void ShowAllInfoButton_Click(object sender, RoutedEventArgs e)
👆

2021-08-03 18:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +                ) continue;
```suggestion
                if (infoBubbleDataPacket.Style != InfoBubbleViewModel.Style.Warning &&
                    infoBubbleDataPacket.Style != InfoBubbleViewModel.Style.WarningCondensed ||
                    ViewModel.DismissedMessages.Contains(infoBubbleDataPacket))
                { 
                    continue; 
                }
```

2021-08-03 18:21 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            var error1 = "Error 1";
move to `Arrange` section

2021-08-03 18:21 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            // Assert
we would probably need to assert the userFacing collections before and after you add to them, otherwise we dont actually know that we successfully added something

2021-08-03 18:21 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            ObservableCollection<InfoBubbleDataPacket> userFacingErrors = infoBubbleViewModel.NodeErrorsToDisplay;
is there actually any point in storing all of these variables?

2021-08-03 18:21 UTC, SHKnudsen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            // Assert
again, we need to actually verify that the things we did had the expected impact so we need to compare the infoBubbleViewModel properties before the change you are doing in this test and after the changes

2021-08-04 08:17 UTC, OliverEGreen commented on src/DynamoCore/Graph/Nodes/NodeModel.cs
> +            new ObservableCollection<OutputMessage>();
Removed this in a subsequent commit to this branch.

2021-08-04 08:17 UTC, OliverEGreen commented on src/DynamoCore/Graph/Nodes/NodeModel.cs
> +            new ObservableCollection<OutputMessage>();
https://github.com/OliverEGreen/Dynamo/pull/4/commits/2ce118a3fe41f97882c5cb65a12c27a9c4ff816f

2021-08-04 08:24 UTC, OliverEGreen commented on src/DynamoCore/Graph/Workspaces/HomeWorkspaceModel.cs
> +                foreach (NodeModel nodeModel in task.ModifiedNodes)
// An event handler we can listen to on the NodeViewModel, to update the 
// node's informational state. This is required because Errors and Warnings 
// currently fire differently from one another.

2021-08-04 08:29 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Themes/Modern/DynamoModern.xaml
> +                              Stroke="{StaticResource MidGreyBrush}" />
will ask!

2021-08-04 08:37 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Core/NodeViewModel.cs
>                  RaisePropertyChanged(nameof(NumberOfDismissedAlerts));
Would it still RaisePropertyChanged? It's being used on the UI for the little dismissed alerts icon at the base of each node.

2021-08-04 09:17 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Themes/Modern/DynamoModern.xaml
> +                              Stroke="{StaticResource MidGreyBrush}" />
Have asked. Will see what they come back with. At least switching icons for images is pretty easy!

2021-08-04 09:25 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        public bool NodeInfoVisible
Just tested, this one doesn't want to work I'm afraid! Not really sure why. Maybe it's not raising PropertyChanged?

2021-08-04 09:55 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        public enum NodeMessageVisibility { Icon, CollapseMessages, ShowAllMessages }
can set to internal, but not private since this gets accessed from the code-behind

2021-08-04 10:04 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +            ZIndex = 40;
Agreed, I've ironed out the ZIndexes in the NodeView (still looks ok) and put this down to 7.

2021-08-04 10:07 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +            if (parameter is InfoBubbleDataPacket infoBubbleDataPacket)
This method used to take a Uri object, rather than an InfoBubbleDataPacket (which is what we're passing now).
Adding in some logic to be able to handle the new case, but not removing any previous functionality in the ViewModel since it's a public API.

2021-08-04 10:08 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        }
I was following the pattern that's been set up here. Agreed it's kinda dumb! 
There's a few of these return true properties.

2021-08-04 10:09 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +                .FirstOrDefault(x => x.Message == value);
I wondered about this. I don't think it's likely to happen (at least with the way errors/warnings work now), and even if it did happen, I'm not totally sure what the desirable functionality is here.

2021-08-04 10:09 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        }
As above following the old pattern here :)

2021-08-04 10:10 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +            for (int i = 0; i < displayErrors.Count; i++) NodeErrorsToDisplay.Add(displayErrors[i]);
Nested these into another method now.

2021-08-04 10:48 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +            switch (nodeMessageVisibility)
Condensed! Should be more readable now, although (I think) this one may always need to be a little condensed.

2021-08-04 10:49 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        }
for these let's not follow the old pattern then, as there is simply no reason to do it. Should be fine to create the command without a CanExecute method

2021-08-04 10:51 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/Preview/InfoBubbleView.xaml.cs
> +            double estimatedWidth)
This is some old code that I think VS decided to line-break. Should I touch it?

2021-08-04 10:59 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        }
It seems the DelegateCommand wants a predicate, not a Boolean. Guess that's been done this way before?

2021-08-04 11:06 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +        }
Should be fine to just use this constructor on the `DelegateCommand`
```csharp
public DelegateCommand(Action<object> execute)
    : this(execute, null)
{
}

only requires an action

2021-08-04 11:28 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +                }
Related to above comment

2021-08-04 12:18 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/Preview/InfoBubbleViewModel.cs
> +            NodeErrorsShowLessMessageVisible = NodeErrorsShowMoreButtonVisible && NodeErrorsVisibilityState == NodeMessageVisibility.ShowAllMessages;
This one also gets set from the code behind, and I can't call RaisePropertyChanged from there in order to update the property.

2021-08-04 13:25 UTC, OliverEGreen commented on src/DynamoCoreWpf/Commands/InfoBubbleCommand.cs
> +                    dismissMessageCommand = new DelegateCommand(DismissMessage, null);
Removed

2021-08-04 13:44 UTC, OliverEGreen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            ObservableCollection<InfoBubbleDataPacket> userFacingErrors = infoBubbleViewModel.NodeErrorsToDisplay;
Just for convenience, it's more readable and they're used a few times in the test body

2021-08-04 13:46 UTC, OliverEGreen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            // Assert
Done

2021-08-04 13:47 UTC, OliverEGreen commented on test/DynamoCoreWpfTests/InfoBubbleTests.cs
> +            // Assert
Added more pre-action assertions

2021-08-04 14:43 UTC, merged