Package manager consumer refresh
OliverEGreen/Dynamo pull request #7
Opened 2021-09-09 15:37 UTC by OliverEGreen

Please Note:
1. Before submitting the PR, please review [How to Contribute to Dynamo](https://github.com/DynamoDS/Dynamo/blob/master/CONTRIBUTING.md)
2. Dynamo Team will meet 1x a month to review PRs found on Github (Issues will be handled separately)
3. PRs will be reviewed from oldest to newest
4. If a reviewed PR requires changes by the owner, the owner of the PR has 30 days to respond. If the PR has seen no activity by the next session, it will be either closed by the team or depending on its utility will be taken over by someone on the team
5. PRs should use either Dynamo's default PR template or [one of these other template options](https://github.com/DynamoDS/Dynamo/wiki/Choosing-a-Pull-Request-Template) in order to be considered for review.
6. PRs that do not have one of the Dynamo PR templates completely filled out with all declarations satisfied will not be reviewed by the Dynamo team.
7. PRs made to the `DynamoRevit` repo will need to be cherry-picked into all the DynamoRevit Release branches that Dynamo supports. Contributors will be responsible for cherry-picking their reviewed commits to the other branches after a `LGTM` label is added to the PR.

### Purpose

(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] User facing strings, if any, are extracted into `*.resx` files
- [ ] All tests pass using the self-service CI.
- [ ] Snapshot of UI changes, if any.
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.
- [ ] This PR modifies some build requirements and the readme is updated

### Reviewers

(FILL ME IN) Reviewer 1  (If possible, assign the Reviewer for the PR)

(FILL ME IN, optional) Any additional notes to reviewers or testers.

### FYIs

(FILL ME IN, Optional) Names of anyone else you wish to be notified of

2021-09-09 16:21 UTC, SHKnudsen requested changes

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        /// A function used to determine whether the used has installed this package already.
`user`?

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
Is the InstallButton not using a command?

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        /// <param name="isPackageInstalledFunction"></param>
Add description to these

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            return IsPackageInstalledProperty;
Thinking about this one, we should have access to the package name from the viewmodel here, right?

If we do, we can remove the packageName argument and just get it directly from the model

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsPackageInstalledProperty
Don't really like that this is called `IsPackageInstalledProperty` can we rename to `IsInstalled`

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        private bool isPackageInstalledProperty;
maybe move this up to the Property

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public void OnCheckIfPackageInstalled()
When is this getting called?

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchViewModel.cs
> +        public DelegateCommand<object> ViewPackageDetailsCommand { get; set; }
Guess this currently dosent do anything?
Might be good to note that

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchViewModel.cs
> +            // to be implemented in future PR
Ah!

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +        public PackageManagerSearchViewModel PackageManagerSearchViewModel { get;  }
consider just calling this `ViewModel` or something, it can get confusing when Properties has the same name as the type

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +            if (!(this.DataContext is PackageManagerSearchViewModel packageManagerSearchViewModel)) return;
how come we dont just use the `ViewModel` property here?

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +            if (!(button.DataContext is PackageDownloadHandle packageDownloadHandle)) return;
same question as above

2021-09-09 16:21 UTC, SHKnudsen commented on src/DynamoPackages/PackageManagerSearchElement.cs
> +
seems like there arent really any changes in this class, so lets just revert it back

2021-09-10 08:34 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Converters.cs
> -                    if (PythonEngineList.IndexOf(dep) != -1)
Good spot! Removed

2021-09-10 08:34 UTC, OliverEGreen commented on src/DynamoCoreWpf/DynamoCoreWpf.csproj
> +      <Private>True</Private>
Reset

2021-09-10 08:34 UTC, OliverEGreen commented on src/AssemblySharedInfoGenerator/AssemblySharedInfo.cs
> +[assembly: AssemblyFileVersion("2.13.0.2374")]
Ah damn I manually turned this one back! Didn't realised it had jumped ahead.

2021-09-10 08:38 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Converters.cs
> +            return booleanValue ? "Installed" : "Install";
Thought I'd got all of these! Added

2021-09-10 08:40 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        /// A function used to determine whether the used has installed this package already.
:D

2021-09-10 08:42 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
As in does it have a CanInstallPackage Boolean value already? 

It seems to use some freaky anonymous method call: 
`this.DownloadLatestCommand = new DelegateCommand(() => OnRequestDownload(Model.Header.versions.Last(), false));`

2021-09-10 08:45 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            return IsPackageInstalledProperty;
I think the reason we had to it in this complex way is we have no access to the PackageSearchManagerViewModel (or Model) from within this class.

2021-09-10 08:46 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            return IsPackageInstalledProperty;
Or do you mean the PackageSearchElementModel? That has the name

2021-09-10 08:46 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            return IsPackageInstalledProperty;
Yeah good point, done!

2021-09-10 08:47 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsPackageInstalledProperty
DOne

2021-09-10 08:48 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        private bool isPackageInstalledProperty;
Done

2021-09-10 08:52 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public void OnCheckIfPackageInstalled()
Never, deleted

2021-09-10 08:53 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +        public PackageManagerSearchViewModel PackageManagerSearchViewModel { get;  }
Updated! 

I actually find it easiest when the type name and object match 👁️

2021-09-10 08:55 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +            if (!(this.DataContext is PackageManagerSearchViewModel packageManagerSearchViewModel)) return;
Updated

2021-09-10 08:57 UTC, OliverEGreen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +            if (!(button.DataContext is PackageDownloadHandle packageDownloadHandle)) return;
On line 179 we do get the ViewModel, but we want access to the PackageDownloadHandle, which comes easiest from the button we're clicking. It's a ListView, so we want the DataContext of the item in the collection. Then we pass that to the command on the VM.

2021-09-10 08:58 UTC, OliverEGreen commented on src/DynamoPackages/PackageManagerSearchElement.cs
> +
Done

2021-09-10 09:05 UTC, OliverEGreen commented on src/DynamoCoreWpf/UI/Converters.cs
> +    /// Used in the Dynamo package manager to hide or show a label next to the package's name.
Added more explanation

2021-09-10 09:06 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        /// <param name="isPackageInstalledFunction"></param>
Added

2021-09-10 09:16 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
Cool, maybe lets just add this check there then.

belive something like this should work:
```csharp
this.DownloadLatestCommand = new DelegateCommand(
    () => OnRequestDownload(Model.Header.versions.Last(), false), 
    () => Model.IsDeprecated && !IsPackageInstalledProperty);

2021-09-10 09:20 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +        public PackageManagerSearchViewModel PackageManagerSearchViewModel { get;  }
Maybe thats actually fine... 
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members?redirectedfrom=MSDN#names-of-properties

I only mentioned it because i remember the Dynamo team commented on it before

2021-09-10 09:20 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +        public PackageManagerSearchViewModel PackageManagerSearchViewModel { get;  }
Also, does this need to be Public?

2021-09-10 09:22 UTC, SHKnudsen commented on src/DynamoCoreWpf/Views/PackageManager/PackageManagerSearchView.xaml.cs
> +            if (!(button.DataContext is PackageDownloadHandle packageDownloadHandle)) return;
Ah i see, i think i just read this to fast and didnt notice this was something else, my bad 🙃

2021-09-10 09:25 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
Should I remove the property? It's being bound to in the view in a few places as well so ideally not :)

2021-09-10 09:27 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
Actually I could go ahead and update those styles to use IsEnabled I guess....

2021-09-10 09:28 UTC, SHKnudsen requested changes
One last comment + one additional response on previous comment after that LGTM

2021-09-10 09:28 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            set
It might make sense the we make the setter for this private, we only really want `IsPackageInstalled()` to update this

2021-09-10 09:33 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
Can't do it, there's stuff outside the button (adjacent to it) which is gonna get real messy if I remove this property.

2021-09-10 09:38 UTC, SHKnudsen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
But couldnt you just bind those other things to `IsInstalled`?

2021-09-10 09:38 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            set
Done

2021-09-10 09:39 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
true, a MultiBinding should do it!

2021-09-10 09:43 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
This means IsInstalled needs to be public btw, since we're binding to it

2021-09-10 09:50 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +            set
Had to undo this since we're binding to it in the view now (see above)

2021-09-10 10:05 UTC, OliverEGreen commented on src/DynamoCoreWpf/ViewModels/PackageManager/PackageManagerSearchElementViewModel.cs
> +        public bool IsInstallButtonEnabled => !Model.IsDeprecated && !IsPackageInstalledProperty;
Done

2021-09-10 10:51 UTC, SHKnudsen approved these changes

2021-09-10 10:53 UTC, SHKnudsen commented
@OliverEGreen just noticed we still have these
![image](https://user-images.githubusercontent.com/13732445/132842952-702eb2cd-4228-4c49-b47a-17c8d35b2230.png)

Are they actually needed?

2021-09-10 10:55 UTC, OliverEGreen commented
> @OliverEGreen just noticed we still have these
> ![image](https://user-images.githubusercontent.com/13732445/132842952-702eb2cd-4228-4c49-b47a-17c8d35b2230.png)
> 
> Are they actually needed?

They are, yeah! I've tried removing them and it won't compile. I think they get set in that new constructor we made.

2021-09-10 10:58 UTC, SHKnudsen commented
> > @OliverEGreen just noticed we still have these
> > ![image](https://user-images.githubusercontent.com/13732445/132842952-702eb2cd-4228-4c49-b47a-17c8d35b2230.png)
> > Are they actually needed?
> 
> They are, yeah! I've tried removing them and it won't compile. I think they get set in that new constructor we made.

Hm, where are they used? I dont think we are actually invoking that event anywhere, think we removed that?

2021-09-10 11:04 UTC, OliverEGreen commented
> > > @OliverEGreen just noticed we still have these
> > > ![image](https://user-images.githubusercontent.com/13732445/132842952-702eb2cd-4228-4c49-b47a-17c8d35b2230.png)
> > > Are they actually needed?
> > 
> > 
> > They are, yeah! I've tried removing them and it won't compile. I think they get set in that new constructor we made.
> 
> Hm, where are they used? I dont think we are actually invoking that event anywhere, think we removed that?

PackageManagerSearchViewModel line 642:

`   element.CheckIfPackageInstalled += this.UserAlreadyHasPackageInstalled;`

2021-09-10 11:10 UTC, SHKnudsen commented
> > > > @OliverEGreen just noticed we still have these
> > > > ![image](https://user-images.githubusercontent.com/13732445/132842952-702eb2cd-4228-4c49-b47a-17c8d35b2230.png)
> > > > Are they actually needed?
> > > 
> > > 
> > > They are, yeah! I've tried removing them and it won't compile. I think they get set in that new constructor we made.
> > 
> > 
> > Hm, where are they used? I dont think we are actually invoking that event anywhere, think we removed that?
> 
> PackageManagerSearchViewModel line 642:
> 
> ` element.CheckIfPackageInstalled += this.UserAlreadyHasPackageInstalled;`

Arh yes, was accidentally searching for the type....

But same question then, are we actually invoking this event anywhere?

2021-09-10 11:17 UTC, SHKnudsen commented
Maybe the invoke shouldn't have been removed?

2021-09-10 11:17 UTC, OliverEGreen commented
> > > > > @OliverEGreen just noticed we still have these
> > > > > ![image](https://user-images.githubusercontent.com/13732445/132842952-702eb2cd-4228-4c49-b47a-17c8d35b2230.png)
> > > > > Are they actually needed?
> > > > 
> > > > 
> > > > They are, yeah! I've tried removing them and it won't compile. I think they get set in that new constructor we made.
> > > 
> > > 
> > > Hm, where are they used? I dont think we are actually invoking that event anywhere, think we removed that?
> > 
> > 
> > PackageManagerSearchViewModel line 642:
> > ` element.CheckIfPackageInstalled += this.UserAlreadyHasPackageInstalled;`
> 
> Arh yes, was accidentally searching for the type....
> 
> But same question then, are we actually invoking this event anywhere?

Hmm... nope seems not! :D 
Removed them.

2021-09-15 10:28 UTC, merged